kind: pipeline
type: exec
name: MyCoreApp

platform:
  os: windows
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
- name: build
  commands:
  - $env:Path += ';C:\Users\andrew_page\AppData\Local\Microsoft\dotnet'
  - "dir env:"
  - $env:path
  - dotnet nuget add source --name nuget.org https://api.nuget.org/v3/index.json
  - dotnet build
  
