kind: pipeline
type: exec
name: MyCoreApp

platform:
  os: windows
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
- name: build
  commands:
  - set PATH=%PATH%;"C:\Users\andrew_page\AppData\Local\Microsoft\dotnet"
  - echo %PATH%
  - cd
  - dotnet build
  
