kind: pipeline
type: exec
name: MyCoreApp

platform:
  os: windows
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
- name: build
  commands:
  - cd C:\Users\andrew_page\AppData\Local\Microsoft\dotnet
  - dir
  - dotnet build
