kind: pipeline
type: exec
name: MyCoreApp

platform:
  os: windows
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world 3
- name: build
  commands:
#  - pwd
#  - "dir env:"
#  - $env:Path += ';C:\Users\andrew_page\AppData\Local\Microsoft\dotnet'
#  - $env:path
#  - "dir env:"
#  - dotnet --list-sdks
   - $env:NUGET_PACKAGES = 'C:\Users\andrew_page\.nuget\packages'
   - dotnet build

- name: publish
  commands:
  - dotnet publish --configuration Release

- name: compress artifact
  commands:
  - Compress-Archive -Path $env:DRONE_WORKSPACE\MyCoreApp\bin\Release\netcoreapp3.1 -DestinationPath C:\Windows\Temp\mycoreapp.$env:CI_BUILD_NUMBER.zip

- name: copy artifact to GCS
  commands:
  - gsutil cp C:\Windows\Temp\mycoreapp.91.zip gs://onotio_windows_artifact/mycoreapp.91.zip
