kind: pipeline
type: exec
name: MyCoreApp

platform:
  os: windows
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
- name: build
  commands:
  - $env:Path += ';C:\Users\andrew_page\AppData\Local\Microsoft\dotnet'
  - $env:path
  - dotnet --list-sdks
  - dotnet nuget list source
  - dotnet add "MyCoreApp" package Microsoft.AspNetCore
  
  
